# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 629d7e2084ab6f9478177d043a18709263a639552c4a4a79a3301bbc5ff7ffd074ef57759a5cc4af06a35c80b2ac97b26750eaea217e77ae4a132a8d30918c84

test:
  secret_key_base: 906a4393100c794178d80ffdb0a8d879f99b80cbd7a62844e543378ac9b233ba40251b160a92ac733f9e155a4e110b8899420613b4c3d9da4987774a77b9a367

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
